import keymirror from "keymirror";

const types = keymirror({
  LAUNCH_MBTA_REQUESTED: null,
  LAUNCH_MBTA_SUCCEEDED: null,
  LAUNCH_MBTA_FAILED: null,

  LAUNCH_BASEBALL_REQUESTED: null,
  LAUNCH_BASEBALL_SUCCEEDED: null,
  LAUNCH_BASEBALL_FAILED: null,
  START_NEW_BASEBALL_REQUESTED: null,
  START_NEW_BASEBALL_SUCCEEDED: null,
  START_NEW_BASEBALL_FAILED: null,
  JOIN_CURRENT_BASEBALL_REQUESTED: null,
  JOIN_CURRENT_BASEBALL_SUCCEEDED: null,
  JOIN_CURRENT_BASEBALL_FAILED: null,
  BASEBALL_CONFIG_REQUESTED: null,
  BASEBALL_CONFIG_SUCCEEDED: null,
  BASEBALL_CONFIG_FAILED: null,
  NEW_BASEBALL_EVENT_REQUESTED: null,
  NEW_BASEBALL_EVENT_SUCCEEDED: null,
  NEW_BASEBALL_EVENT_FAILED: null,
  UNDO_STRIKE: null,

  LAUNCH_PERSON_PICKER_REQUESTED: null,
  LAUNCH_PERSON_PICKER_SUCCEEDED: null,
  LAUNCH_PERSON_PICKER_FAILED: null,
  PICK_PERSON_REQUESTED: null,
  PICK_PERSON_SUCCEEDED: null,
  PICK_PERSON_FAILED: null,

  FETCH_PLAYLIST_SONGS_REQUESTED: null,
  FETCH_PLAYLIST_SONGS_SUCCEEDED: null,
  FETCH_PLAYLIST_SONGS_FAILED: null,
  FETCH_SEARCH_SONGS_REQUESTED: null,
  FETCH_SEARCH_SONGS_SUCCEEDED: null,
  FETCH_SEARCH_SONGS_FAILED: null,
  ADD_SONG_REQUESTED: null,
  ADD_SONG_SUCCEEDED: null,
  ADD_SONG_FAILED: null,
  PLAY_SONG_REQUESTED: null,
  PLAY_SONG_SUCCEEDED: null,
  PLAY_SONG_FAILED: null,
  FETCH_CURRENTLY_PLAYING_REQUESTED: null,
  FETCH_CURRENTLY_PLAYING_SUCCEEDED: null,
  FETCH_CURRENTLY_PLAYING_FAILED: null
});

export default types;
