
const types = {
  LAUNCH_MBTA_REQUESTED: 'LAUNCH_MBTA_REQUESTED',
  LAUNCH_MBTA_SUCCEEDED: 'LAUNCH_MBTA_SUCCEEDED',
  LAUNCH_MBTA_FAILED: 'LAUNCH_MBTA_FAILED',

  LAUNCH_BASEBALL_REQUESTED: 'LAUNCH_BASEBALL_REQUESTED',
  LAUNCH_BASEBALL_SUCCEEDED: 'LAUNCH_BASEBALL_SUCCEEDED',
  LAUNCH_BASEBALL_FAILED: 'LAUNCH_BASEBALL_FAILED',
  START_NEW_BASEBALL_REQUESTED: 'START_NEW_BASEBALL_REQUESTED',
  START_NEW_BASEBALL_SUCCEEDED: 'START_NEW_BASEBALL_SUCCEEDED',
  START_NEW_BASEBALL_FAILED: 'START_NEW_BASEBALL_FAILED',
  JOIN_CURRENT_BASEBALL_REQUESTED: 'JOIN_CURRENT_BASEBALL_REQUESTED',
  JOIN_CURRENT_BASEBALL_SUCCEEDED: 'JOIN_CURRENT_BASEBALL_SUCCEEDED',
  JOIN_CURRENT_BASEBALL_FAILED: 'JOIN_CURRENT_BASEBALL_FAILED',
  BASEBALL_CONFIG_REQUESTED: 'BASEBALL_CONFIG_REQUESTED',
  BASEBALL_CONFIG_SUCCEEDED: 'BASEBALL_CONFIG_SUCCEEDED',
  BASEBALL_CONFIG_FAILED: 'BASEBALL_CONFIG_FAILED',
  NEW_BASEBALL_EVENT_REQUESTED: 'NEW_BASEBALL_EVENT_REQUESTED',
  NEW_BASEBALL_EVENT_SUCCEEDED: 'NEW_BASEBALL_EVENT_SUCCEEDED',
  NEW_BASEBALL_EVENT_FAILED: 'NEW_BASEBALL_EVENT_FAILED',
  LAUNCH_PERSON_PICKER_REQUESTED: 'LAUNCH_PERSON_PICKER_REQUESTED',
  UNDO_STRIKE: 'UNDO_STRIKE',

  PICK_PERSON_REQUESTED: 'PICK_PERSON_REQUESTED',
  PICK_PERSON_SUCCEEDED: 'PICK_PERSON_SUCCEEDED',
  PICK_PERSON_FAILED: 'PICK_PERSON_FAILED'
};

export default types;