
const types = {
  START_NEW_GAME_REQUESTED: 'START_NEW_GAME_REQUESTED',
  START_NEW_GAME_SUCCEEDED: 'START_NEW_GAME_SUCCEEDED',
  START_NEW_GAME_FAILED: 'START_NEW_GAME_FAILED',
  GAME_CONFIG_REQUESTED: 'GAME_CONFIG_REQUESTED',
  GAME_CONFIG_SUCCEEDED: 'GAME_CONFIG_SUCCEEDED',
  GAME_CONFIG_FAILED: 'GAME_CONFIG_FAILED',

  // Temporary. Will add other actions later
  NEW_GAME_EVENT: 'NEW_GAME_EVENT'
};

export default types;